<?php
if(isset($_SESSION['zprava']))
{
	echo "<span id='zprava'>".$_SESSION['zprava']."</span>";
	session_destroy();
}
?>
<form method="post">
	<strong>Řazení:</strong>
	<select name="razeni">
	  	<option value="cena">Od nejlevnějšího</option>
	  	<option value="cena DESC">Od nejdražšího</option>
	  	<option value="nazev">Abecedně A-Z</option>
	  	<option value="nazev DESC">Abecedně Z-A</option>
	</select>
	<input type="submit" value="Zobrazit">
</form>
<table id="nabidka">
<?php

$pocetProduktu = 0;
while(isset($this->data[$pocetProduktu])){
	echo "<tr>";
	for( $j = 0;$j<3;$j++)
	{
	if(isset($this->data[$pocetProduktu])){
	$img = "obrazky/not.jpg";
	if(file_exists("obrazky/{$this->data[$pocetProduktu]['id']}small.png"))
	$img = 	"obrazky/{$this->data[$pocetProduktu]['id']}small.png";
	echo <<<EOT
<td>
	<table class="produkt" >
		<tr><td colspan="2"><a href="index.php?strana=Produkt&id={$this->data[$pocetProduktu]['id']}">{$this->data[$pocetProduktu]['nazev']}</a></td></tr>
		<tr><td colspan="2"><a href="index.php?strana=Produkt&id={$this->data[$pocetProduktu]['id']}"><img src="$img"></a></td></tr>
		<tr><td>{$this->data[$pocetProduktu]['cena']} Kč</td><td><a href="index.php?id={$this->data[$pocetProduktu]['id']}"><span>Koupit</span></a></td></tr>
	</table>
</td>
EOT;
	$pocetProduktu++;
	}
	}
	echo "</tr>";
}
?>
</table>

<?php if($_SESSION['idUzivatel'] != 0) {

echo '<form method="post">'.
	    '<table>'.
	    	'<tr>'.
			'<td>'.'<label for="nazev">Název:</label>'.'</td>'.
			'<td>'.'<input type="text" name="nazev">'.'</td>'.'</tr>'.

			'<td>'.'<label for="popis">Popis:</label>'.'</td>'.
			'<td>'.'<input type="text" name="popis">'.'</td>'.'</tr>'.

			'<td>'.'<label for="kategorie">Kategorie:</label>'.'</td>'.
			'<td>'.'<input type="text" name="kategorie">'.'</td>'.'</tr>'.

			'<td>'.'<label for="cena">Cena:</label>'.'</td>'.
			'<td>'.'<input type="text" name="cena">'.'</td>'.'</tr>'.

			'<tr>'.'<td>'.'<input type="submit" value="Přidat produkt" name="pridatProdukt">'.'</td>'.'</tr>'.
		  '</table>'.
'</form>';
 } ?>

