<h3><?= $this->data['nazev']?></h3>
<?php
	$img = "obrazky/not.jpg";
	if(file_exists("obrazky/{$this->data['id']}small.png"))
	$img = 	"obrazky/{$this->data['id']}small.png";
	echo "<img src='$img'>";

?>
	<p><?= $this->data['popis']?></p>
<table id="Koupit">
	<tr>
		<td><h4>Cena: <?= $this->data['cena']?> Kč</h4></td>
		<td><h3><a href="index.php?id=<?=$this->data['id']?>">Koupit</a></h3></td>
	</tr>
</table>
<br>



<a href="index.php">Zpět na nabídku</a>


<?php if($_SESSION['idUzivatel'] != 0) {
	$pom = $this->data['id'];

	echo '<a href="index.php?strana=Produkt&id='.$pom.'&delete=true">Odstranit</a>';

echo '<form method="post">'.
	    '<table>'.
	    	'<tr>'.
			'<td>'.'<label for="nazev">Název:</label>'.'</td>'.
			'<td>'.'<input type="text" name="nazev" value="'.htmlspecialchars($this->data['nazev']).'">'.'</td>'.'</tr>'.

			'<td>'.'<label for="popis">Popis:</label>'.'</td>'.
			'<td>'.'<input type="text" name="popis" value="'.htmlspecialchars($this->data['popis']).'">'.'</td>'.'</tr>'.

			'<td>'.'<label for="kategorie">Kategorie:</label>'.'</td>'.
			'<td>'.'<input type="text" name="kategorie" value="'.htmlspecialchars($this->data['kategorie']).'">'.'</td>'.'</tr>'.

			'<td>'.'<label for="cena">Cena:</label>'.'</td>'.
			'<td>'.'<input type="text" name="cena" value="'.htmlspecialchars($this->data['cena']).'">'.'</td>'.'</tr>'.

			'<tr>'.'<td>'.'<input type="submit" value="Upravit produkt" name="upravitProdukt">'.'</td>'.'</tr>'.
		  '</table>'.
'</form>';
 } ?>




