<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="generator" content="PSPad editor, www.pspad.com">
  <link rel="stylesheet" type="text/css" href="pohledy/design/minecraftCSS.css">
  <link href="pohledy/design/styles.css" rel="stylesheet" type="text/css">
  <title><?= $this->titulek ?></title>

  <script type="text/javascript">
  </script>

  </head>
  <body>

  <div id="prihlasovani1">

  <table>

    <tr>
      <td class="prihlasovani2"><a href="/ES/kontrolery/PrihlaseniKontroler">Přihlášení- </a></td>
      <td class="prihlasovani2"><a href="/ES/kontrolery/PrihlaseniKontroler"> -Registrace</a></td>
    <tr>

  </table>

  </div>

  <center><a href="index.php"><img src="obrazky/nadpis2.png"></a></center>




  <div id="hlavni_stranka">


     <div id="cssmenu">
		<ul>
		   <li><a href='index.php'><span>Úvodní strana</span></a></li>
		  <li class='has-sub '><a href='#'><span>Kategorie</span></a>
					<ul>
						<li><a href="index.php">Vše</a></li>
						<li><a href="index.php?kat=Saxofony">Saxofony</a></li>
						<li><a href="index.php?kat=Platky">Plátky</a></li>
						<li><a href="index.php?kat=Prislusenstvi">Příslušenství</a></li>
					</ul>
		  </li>

		     <li class='has-sub '><a href="index.php?strana=Kosik"><span>Nákupní košík</span></a></li>

		</ul>
	</div>

<!--
 -------------------------------------------------------------------------------
-->
<br>
	<div id="content">

			<article>
				<?php
				require ("pohledy/$this->pohled.phtml");
				?>
			</article>

	</div>
</div>
  </body>
</html>
