<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="generator" content="PSPad editor, www.pspad.com">
  <link rel="stylesheet" type="text/css" href="pohledy/design/minecraftCSS.css">
  <link href="pohledy/design/styles.css" rel="stylesheet" type="text/css">
  <title><?= $this->titulek ?></title>

  <script type="text/javascript">
  </script>

  </head>
  <body>

  <div id="prihlasovani1">

  <table>
<?php
  include "modely/uzivatel.php";

// kdyz ma uzivatel ID 0 -> neregistrovany uzivatel
if($_SESSION['idUzivatel'] == 0) {
  echo '<tr>'.
       '<td class="prihlasovani2">'.
       '<a style="color:white;" href="index.php?strana=Prihlaseni">|Přihlásit se </a>'.
       '<a style="color:white;" href="index.php?strana=Registrace"> | Zaregistrovat se|</a>'.
       '</td>'.
  	   '</tr>';
}
// jinak ID jine nez 0 -> prihlaseny uzivatel
else {


echo  '<form method="get">'.
      '<tr>'.
      '<td class="prihlasovani2">'.
      'Ahoj: '.$_SESSION['jm'].'<input value="odhlásit" type="submit" name="odhlasit">'.
      '</td>'.
      '</tr>'.
      '</form>';


	if(isset($_GET['odhlasit']))
	{
		session_destroy();
		header("location: index.php");
		exit;
	}

}

?>
  </table>

  </div>

  <center><a href="index.php"><img src="obrazky/nadpis2.png"></a></center>




  <div id="hlavni_stranka">

     <div id="cssmenu">
		<ul>
		   <li><a href='index.php'><span>Úvodní strana</span></a></li>
		  <li class='has-sub '><a href='#'><span>Kategorie</span></a>
					<ul>
						<li><a href="index.php">Vše</a></li>
						<li><a href="index.php?kat=Bojovky">Bojovky</a></li>
						<li><a href="index.php?kat=Scifi">Sci-fi</a></li>
						<li><a href="index.php?kat=Horor">Horor</a></li>
					</ul>
		  </li>


		    <li class='has-sub '><a href="index.php?strana=Kosik"><span>Nákupní košík (<?php if(isset($this->cena)) echo $this->cena; else echo "0"?> Kč)</span></a></li>

		     <?php if($_SESSION['idUzivatel'] != 1 && $_SESSION['idUzivatel'] != 0) {

		     	echo '<li class="has-sub">'.
				    '<a href="index.php?strana=Objednavky">'.
				    '<span>Přehled objednávek</span>'.
				    '</a>'.
				    '</li>';

		     }?>


		</ul>
	</div>

<!--
 -------------------------------------------------------------------------------
-->
<br>
	<div id="content">

			<article>
				<?php
				require ("pohledy/$this->pohled.phtml");
				?>
			</article>

	</div>
</div>
  </body>
</html>
